name: CD Pipeline
on:
  workflow_run:
    workflow: ["CI Pipeline"]
    type:
      - completed

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Pull docker image
        run: sudo docker pull ${{ secrets.DOCKER_USERNAME }}/${{ vars.REPO_NAME}}:latest

      - name: Delete OLD docker container
        run: sudo docker rm -f {{ vars.REPO_NAME}}-container || true

      - name: Run docker container
        run: sudo docker run -d -p 4201:4200 --name {{ vars.REPO_NAME}}-container ${{ secrets.DOCKER_USERNAME }}/${{ vars.REPO_NAME}}